#!/usr/bin/env bash
# gen_golden.sh — capture per-version golden data from the real PUC-Rio
# reference binaries ONCE, into committed golden files the kits assert against.
#
# This is the "capture the reference truth, freeze it" half of the golden-kit
# pattern (see ../CLAUDE.md "fast iteration tools"): the kit then runs purely
# in-process against the frozen golden with NO reference binary, NO subprocess,
# NO /tmp dependency — so it works in CI and on wasm.
#
# Regenerate when you extend a battery or bump a pinned reference:
#   bash harness/gen_golden.sh
#
# Reference binaries: /tmp/lua-refs/bin/lua5.{1.5,2.4,3.6,4.7,5.5.0}
# (rebuild per specs/oracle/CONTRACT.md if /tmp was cleared).
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GOLDEN_DIR="$ROOT/crates/lua-rs-runtime/tests/golden"
mkdir -p "$GOLDEN_DIR"

refbin() { case "$1" in
  5.1) echo /tmp/lua-refs/bin/lua5.1.5;;
  5.2) echo /tmp/lua-refs/bin/lua5.2.4;;
  5.3) echo /tmp/lua-refs/bin/lua5.3.6;;
  5.4) echo /tmp/lua-refs/bin/lua5.4.7;;
  5.5) echo /tmp/lua-refs/bin/lua5.5.0;;
esac; }

# ── dump header golden ──────────────────────────────────────────────────────
# Header length is format-fixed per version (signature+version+format+sizes
# +sentinels), independent of the dumped function. Only the header is captured
# because the BODY format for 5.1/5.2 differs structurally from our internal
# (5.4-shaped) body — full cross-binary body fidelity is out of scope; the kit
# pins the header bytes (what calls.lua checks) and self-roundtrip.
hdr_len() { case "$1" in 5.1) echo 12;; 5.2) echo 18;; 5.3) echo 33;; 5.4) echo 31;; 5.5) echo 40;; esac; }

DUMP_GOLDEN="$GOLDEN_DIR/dump_headers.tsv"
: > "$DUMP_GOLDEN"
echo "# version<TAB>header_len<TAB>hex_bytes  (generated by harness/gen_golden.sh)" >> "$DUMP_GOLDEN"
for v in 5.1 5.2 5.3 5.4 5.5; do
  ref="$(refbin "$v")"; n="$(hdr_len "$v")"
  [ -x "$ref" ] || { echo "MISSING $ref" >&2; continue; }
  hex=$("$ref" -e 'io.write(string.dump(function() return 1 end))' 2>/dev/null | head -c "$n" | od -An -tx1 | tr -d ' \n')
  printf '%s\t%s\t%s\n' "$v" "$n" "$hex" >> "$DUMP_GOLDEN"
  echo "dump $v: $hex"
done
echo "wrote $DUMP_GOLDEN"
