#!/usr/bin/env bash
# Generate ANALYSES/version_feature_matrix.tsv — the reference-backed source of
# record for LuaVersion::supports (issue #234). Each cell is produced by probing
# the REFERENCE Lua binary for that version (never our own engine, which would be
# circular once init.rs consumes the matrix). The probes match
# specs/ISSUE_234_BACKEND_SEAM_SPEC.md §2.3; every probe is pcall-guarded and
# loads source via `loadstring or load` so it is Lua-5.1-safe.
#
# Usage: bash specs/oracle/gen_feature_matrix.sh   (writes the TSV, prints a diff)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/ANALYSES/version_feature_matrix.tsv"

choose_ref() { [ -x "$1" ] && echo "$1" || echo "$2"; }
ref_for() {
  case "$1" in
    5.1) echo "${LUA_RS_REF_51:-/tmp/lua-refs/bin/lua5.1.5}" ;;
    5.2) echo "${LUA_RS_REF_52:-/tmp/lua-refs/bin/lua5.2.4}" ;;
    5.3) echo "${LUA_RS_REF_53:-$(choose_ref "$ROOT/reference/lua-5.3.6/src/lua" /tmp/lua-refs/bin/lua5.3.6)}" ;;
    5.4) echo "${LUA_RS_REF_54:-$(choose_ref "$ROOT/reference/lua-5.4.7/src/lua" /tmp/lua-refs/bin/lua5.4.7)}" ;;
    5.5) echo "${LUA_RS_REF_55:-$(choose_ref "$ROOT/reference/lua-5.5.0/src/lua" /tmp/lua-refs/bin/lua5.5.0)}" ;;
  esac
}

# The probe program: prints `<Feature>\t<0|1>` per row for whichever interpreter
# runs it. 5.1-safe (loadstring fallback, no modern syntax outside loaded strings).
read -r -d '' PROBE <<'LUA' || true
local loadit = loadstring or load
local function parses(src)
  local ok, fn = pcall(loadit, src)
  return ok and fn ~= nil
end
local function typeis(expr, ty)
  local ok, fn = pcall(loadit, "return " .. expr)
  if not (ok and fn) then return false end
  local ok2, v = pcall(fn)
  return ok2 and type(v) == ty
end
local function gcopt(...)
  return (pcall(collectgarbage, ...))
end
local function env_sandbox()
  local ok1, f1 = pcall(loadit, "local _ENV = {x=3}; return x")
  local a = ok1 and f1 and select(1, (function() local o,v = pcall(f1); return o and v == 3 end)())
  local ok2, f2 = pcall(loadit, "return y", nil, nil, {y = 4})
  local b = ok2 and f2 and select(1, (function() local o,v = pcall(f2); return o and v == 4 end)())
  return a and b
end
local function table_len_mm()
  local ok, v = pcall(function()
    return #setmetatable({}, {__len = function() return 42 end})
  end)
  return ok and v == 42
end
local probes = {
  {"IntegerSubtype",     function() return typeis("math.type", "function") end},
  {"EnvSandbox",         env_sandbox},
  {"FenvSandbox",        function() return typeis("setfenv","function") and typeis("getfenv","function") end},
  {"GotoLabels",         function() return parses("do goto l ::l:: end") end},
  {"NativeBitwise",      function() return parses("return (6 & 3) ~ (1 << 2) // 1") end},
  {"Bit32Lib",           function() return typeis("bit32", "table") end},
  {"Utf8Lib",            function() return typeis("utf8", "table") end},
  {"StringPack",         function() return typeis("string.pack","function") and typeis("string.unpack","function") and typeis("string.packsize","function") end},
  {"CloseAttribute",     function() return parses("local x <close> = nil") end},
  {"ConstAttribute",     function() return parses("local x <const> = 1") end},
  {"CoroutineClose",     function() return typeis("coroutine.close", "function") end},
  {"WarnFunction",       function() return typeis("warn", "function") end},
  {"TableLenMetamethod", table_len_mm},
  {"GcIsRunning",        function() return gcopt("isrunning") end},
  {"GcParam",            function() return gcopt("param", "pause") end},
  {"GlobalKeyword",      function() return parses("global g = 1") end},
  {"NamedVararg",        function() return parses("local function f(a, ...t) end") end},
  {"TableCreate",        function() return typeis("table.create", "function") end},
}
for _, p in ipairs(probes) do
  local ok, res = pcall(p[2])
  io.write(p[1], "\t", (ok and res) and "1" or "0", "\n")
end
LUA

TMP="$(mktemp)"
{
  echo "# version_feature_matrix.tsv — issue #234 capability matrix."
  echo "# GENERATED by specs/oracle/gen_feature_matrix.sh from the REFERENCE binaries."
  echo "# Do not hand-edit; regenerate. Columns: version<TAB>feature<TAB>supported(0|1)."
  for v in 5.1 5.2 5.3 5.4 5.5; do
    ref="$(ref_for "$v")"
    [ -x "$ref" ] || { echo "missing reference binary for $v: $ref" >&2; exit 2; }
    while IFS=$'\t' read -r feat val; do
      printf '%s\t%s\t%s\n' "$v" "$feat" "$val"
    done < <("$ref" -e "$PROBE")
  done
} > "$TMP"

if [ -f "$OUT" ] && ! diff -q "$OUT" "$TMP" >/dev/null; then
  echo "== matrix changed vs committed fixture ==" >&2
  diff "$OUT" "$TMP" >&2 || true
fi
mv "$TMP" "$OUT"
echo "wrote $OUT ($(grep -cv '^#' "$OUT") rows)"
